cluster.name: "elk"
network.host: 0.0.0.0

xpack.security.enabled: true
xpack.license.self_generated.type: basic
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false
xpack.security.authc.api_key.enabled: true
xpack.security.enrollment.enabled: false